### ISSUE TITLE
Remove option is incompatible with 117HD

### ISSUE THREAD

**Issue by Makaro1** [Jmmuir/Fairy-Ring-Butterflies#1]
When using the Fairy Ring Butterflies plug-in with the 117HD plug-in, the butterflies turn red. Neither removing or recolouring them seems possible while 117HD is also active. Is compatibility with 117HD possible?

Thank you for your plug-in regardless!

**Comment by Jmmuir** [comment]
Hi,

I tested this on my own machine with 117HD on and it appears to work fine?

![](https://i.imgur.com/oAj6vV6.png)

Can you let me know which 117HD settings you're using, and which ring you're seeing the issue with?

This plugin only changes the model colours, so it shouldn't conflict. Have you tried restarting the client with both enabled?

**Comment by Makaro1** [comment]
Thanks for the response. Glad to know it is on my end.

I am seeing the issue with all rings. When I turn 117HD off the plug-in works as intended. But when it is on I see this: 
![2](https://user-images.githubusercontent.com/128003161/225511628-5fe969b7-dc94-4a32-9d12-30dbdced6934.png)

Changing colours also changes nothing
![3](https://user-images.githubusercontent.com/128003161/225511674-4646a7fa-ffa2-4aaf-b9b9-9c805c5c40e4.png)

Here are my 117HD settings. I have messed with several ones in attempt to change something but no successes here.

![1](https://user-images.githubusercontent.com/128003161/225511864-76bcbc08-9543-457f-8af0-00e141a13aa7.png)

I have also restarted RuneLite a few times with both plug-ins enabled.
Thanks again!

**Comment by Jmmuir** [comment]
Ah yes, thanks for this.

I see the issue now. It's specific to the removal option- under the hood this just recolours the butterflies with a colour code of -1, which the default renderer interprets as invisible, but it appears the 117HD plugin changes something that makes it render as red instead.

since, secretly, the removal option is just a "recolour", it takes precedence over any colours you have set, which is why that didn't seem to be working for you either. If you untick the hide option you'll find that the recolour settings should work for you on HD.

No promises, but I'll look into getting the remove option to work with the HD plugin, see if I can find a way to make both renderers happy.

**Comment by Jmmuir** [comment]
Fixed on latest- found a colour code that works for both standard and HD to remove the butterflies.

@Makaro1 You'll need to wait for the changes to be pulled by the plugin hub
