### ISSUE TITLE
Configuration suggestion

### ISSUE THREAD

**Issue by peet99** [Jmmuir/Fairy-Ring-Butterflies#2]
I relly like this plugin it brings some extra extra you know, but the configuration takes vary long, have you already thought about default settings. Or a way to import them from others? 

 I'll donate you five dollars for the amazing plugin! <3

![image](https://github.com/Jmmuir/Fairy-Ring-Butterflies/assets/63288740/eefe872c-596d-4bb1-8e15-fe581d745075)

**Comment by peet99** [comment]
I dont know how to support you guys with a little money...

**Comment by Jmmuir** [comment]
I'm glad you like it! No need to donate, I made this for me, sharing it is just trying to give something back.

I will look into some kind of import/export function, and perhaps change the defaults (at least for the biome settings) to something a bit more exciting.

Thanks for the feedback :)

**Comment by Jmmuir** [comment]
I've added a basic import/export feature if you want to share between your friends.

Default config is also now what my own config is, rather than defaulting to the appearance without the plugin. That should make it a little less tedious to set up in the first instance.

Changes will be available in live runelite once they're reviewed by the team there.
