### ISSUE TITLE
Issues with plugin after recent update

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Jmmuir/Fairy-Ring-Butterflies#3]
The plugin seems to malfunction and not function after the recent update that added Scurrius.

**Comment by Jmmuir** [comment]
Hi, can you be more specific as to the issue you're seeing?

There was a period on update day when the API wasn't working yet, but since then it has been working fine whenever I've passed a ring.

Are the butterflies not being recoloured? What distance are you from rings at the time?

Screenshots would be helpful if you can get them.

**Comment by Jin-Jiyunsun** [comment]
It seems have resolved on its own, it wasnt recolouring them (hiding, specifically) but its working fine now. I suppose it was as you mentioned with the API.

**Comment by Jmmuir** [comment]
I looked into it and you were actually right. I've fixed it though and you should no longer have issues with recolouring after visiting scurrius, once the change is merged in.

If you're interested in what happened:

The arceuus ring used to have a different ID from the other rings in game, presumably to facilitate it changing when you paid for it to be fixed.

With the favour removal update, they changed the fairy ring there to be a regular one.

With the scurrius update, they had reused the ID that previously was assigned to the arceuus ring, which meant that the plugin was detecting whatever it was they added to the sewer as a fairy ring and attempting to recolour it, which it would fail to do and cause it to crash each time.

**Comment by Jin-Jiyunsun** [comment]
Ah, thanks for the fix!
